pipelines:
  branches:
    main:
      - step:
          name: Sync GitHub Mirror
          image: node:20.5.0
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:sreedhar_ramasamy/fingrid-tracker.git
            - cd fingrid-tracker.git
            - git push --mirror git@github.com:Harishlucifer/fingrid-tracker.git